spring:
  profiles:
    active: dev
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      #单个文件的最大值
      max-file-size: 100MB
      #上传文件总的最大值
      max-request-size: 200MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xcc.entity
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

sa-token:
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  token-style: random-128
  # 是否输出操作日志
  is-log: false
