server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:local-ssl.p12
    key-store-password: shuaidaobaozha7
    key-store-type: PKCS12
    key-alias: local_ssl

spring:
  application:
    name: huoban-yunke
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/huoban?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  web:
    resources:
      static-locations: file:${upload}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO

upload: E:/huoban-uploads
